# Generated by Django 5.2.12 on 2026-03-29 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('region', models.CharField(choices=[('middle_east', 'Middle East'), ('east_africa', 'East Africa'), ('west_africa', 'West Africa'), ('north_africa', 'North Africa'), ('central_africa', 'Central Africa'), ('south_asia', 'South Asia'), ('central_asia', 'Central Asia'), ('southeast_asia', 'Southeast Asia'), ('eastern_europe', 'Eastern Europe'), ('south_america', 'South America'), ('central_america', 'Central America'), ('oceania', 'Oceania'), ('other', 'Other')], max_length=50)),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=3)),
                ('risk_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Elevated'), (4, 'High'), (5, 'Extreme')], default=3)),
                ('summary', models.TextField(help_text='Brief description shown on cards', max_length=500)),
                ('overview', models.TextField(help_text='Detailed destination overview')),
                ('safety_brief', models.TextField(help_text='Current safety situation and risks')),
                ('visa_info', models.TextField(blank=True, help_text='Visa and entry requirements')),
                ('transport_info', models.TextField(blank=True, help_text='How to get there and get around')),
                ('money_info', models.TextField(blank=True, help_text='Currency, ATMs, costs')),
                ('connectivity_info', models.TextField(blank=True, help_text='Phone, internet, SIM cards')),
                ('tips', models.TextField(blank=True, help_text='Practical tips and advice')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('emoji_icon', models.CharField(default='🌍', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('last_verified', models.DateField(blank=True, help_text='When the info was last verified as current', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'edgetravel_destinations',
                'ordering': ['-risk_level', 'name'],
            },
        ),
    ]
