# Generated by Django 5.2.12 on 2026-03-29 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('post_anonymously', models.BooleanField(default=False, help_text='Hide your username on this report')),
                ('trip_start', models.DateField(blank=True, null=True)),
                ('trip_end', models.DateField(blank=True, null=True)),
                ('travel_style', models.CharField(choices=[('solo', 'Solo'), ('partner', 'With Partner'), ('group', 'Small Group'), ('guided', 'Guided Tour'), ('journalism', 'Journalism/Work')], default='solo', max_length=50)),
                ('body', models.TextField(help_text='Your full trip report')),
                ('tips', models.TextField(blank=True, help_text='Key tips for others')),
                ('safety_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='How safe did you feel? 1=very unsafe, 5=very safe')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('moderation_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reports', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reports', to='destinations.destination')),
            ],
            options={
                'db_table': 'edgetravel_trip_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=5000)),
                ('post_anonymously', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.tripreport')),
            ],
            options={
                'db_table': 'edgetravel_report_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reports.tripreport')),
            ],
            options={
                'db_table': 'edgetravel_report_votes',
                'unique_together': {('user', 'report')},
            },
        ),
    ]
